name: samrt_health
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  liquid_swipe: ^2.1.0
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  shared_preferences:
  mask_text_input_formatter: ^2.0.0
  lottie: ^1.1.0
  flutter_bloc: ^7.2.0
  easy_localization:
  animated_theme_switcher: ^2.0.1
  circular_reveal_animation: ^2.0.0
  freezed_annotation:
  injectable:
  animated_bottom_navigation_bar: ^0.3.2
  url_launcher: ^6.0.9
  firebase_auth:
  google_sign_in: ^5.2.1
  cloud_firestore:
  firebase_core: ^1.8.0
  font_awesome_flutter: ^9.2.0
  firebase_database: ^8.0.1
  flutter_signin_button: ^2.0.0
  flutter_facebook_auth: "^3.5.2"
  flutter_local_notifications: ^9.0.3
  device_info: ^2.0.2
  flutter_device_type: ^0.4.0
  flutter_native_timezone: ^2.0.0
  image: ^3.0.8
  rxdart: ^0.27.2
  http: ^0.13.4
  devicelocale: ^0.5.0
  translator: ^0.1.7
  html_unescape: ^2.0.0
  flutter_localizations: # Add this line
    sdk: flutter
  weight_slider: ^1.2.2
  responsive_grid: ^2.0.0
  fluid_kit: ^2.0.3
  syncfusion_flutter_sliders: ^19.3.54
  sleek_circular_slider: ^2.0.1
  syncfusion_flutter_datepicker: ^19.3.54
  flutter_picker: ^2.0.2
  numberpicker: ^2.1.1
  gender_picker: ^1.1.0
  material_segmented_control: ^3.1.2
  charts_flutter: ^0.12.0
  sensors: ^2.0.3
  file_picker: ^4.1.5
  image_cropper: ^1.4.1
  adaptive_action_sheet: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_native_splash:
  color: "#B085F5"
  image: assets/img/splash.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/animation/
    - assets/translations/
    - icons/
    - sound/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
